name: Build and Deploy Java Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Build with Maven
      run: mvn clean install
      
    -  name: Upload WAR file as artfact
       uses: actions/upload-artifact@v3
       with:
         name: my-app-war
         path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download WAR file artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app-war
        path: ./deploy

    - name: Deploy to Tomcat
      run: |
        curl --upload-file ./deploy*.war "https://${{ secrets.TOMCAT_SERVER_URL }}:${{ secrets.TOMCAT_PORT}}/manage/text/deploy?path=/myapp&update=true" --user "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}"
      env:
        TOMCAT_SERVER_URL: ${{ secrets.TOMCAT_SERVER_URL }}
        TOMCAT_PORT: ${{ secrets.TOMCAT_PORT}}
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}

         
      
